spring:
  application:
    name: billing-service
  main:
    allow-bean-definition-overriding: true 
  datasource:
    url: jdbc:postgresql://postgres:5432/billingdb
    username: myheart
    password: myheart123
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
  
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: myheart
    password: myheart123

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
  
  cloud:
    consul:
      enabled: true
      host: consul
      port: 8500
      discovery:
        enabled: true
        register: true
        prefer-ip-address: true
        health-check-path: /actuator/health
        health-check-interval: 15s
        instance-id: ${spring.application.name}:${random.value} 

server:
  port: 8085

logging:
  level:
    com.myheart: INFO

patient:
  service:
    url: http://patient-service:8082

appointment:
  service:
    url: http://appointment-service:8084

# billing-service - À AJOUTER
resilience4j:
  circuitbreaker:
    instances:
      patientService:
        registerHealthIndicator: true
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        permittedNumberOfCallsInHalfOpenState: 3
        waitDurationInOpenState: 10s
        failureRateThreshold: 50
      appointmentService:
        registerHealthIndicator: true
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        permittedNumberOfCallsInHalfOpenState: 3
        waitDurationInOpenState: 10s
        failureRateThreshold: 50

  timelimiter:
    instances:
      patientService:
        timeoutDuration: 5s
      appointmentService:
        timeoutDuration: 5s

  retry:
    instances:
      patientService:
        maxAttempts: 3
        waitDuration: 1s
        retryExceptions:
          - org.springframework.web.client.HttpServerErrorException
      appointmentService:
        maxAttempts: 3
        waitDuration: 1s

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus,circuitbreakers